spring:
  profiles:
    active: dev


logging:
  charset:
    console: UTF-8
---
# 生产环境
spring:
  on-profiles: pro
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/newRBS?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: 12345678


logging:
  level:
    root: warn

---
# 开发环境
spring:
  on-profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/rbs?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: 12345678
logging:
  level:
    root: debug


#logging:
#  file:
#    name: server.log
#  logback:
#    rollingpolicy:
#      # 设置log文件的最大大小，超过1MB自动存储为新文件
#      max-file-size: 1MB
#      # 设置log文件命名规则：server.日期.序号.log
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log

