spring:
#  datasource:
#    url: jdbc:mysql://211.64.28.110:3306/RBS?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: Udkklzxc123.
  datasource:
    url: jdbc:mysql://106.15.196.199:3306/RBS?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 5236169Zz.

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl